<?php

namespace Odepax\MarsPeacock;

abstract class Feature
{
	const NONE = 0;

	const UNDERLINING = 1;
	const DOUBLE_UNDERLINING = 2;
	const UNDERWAVING = 3;
	const STRIKING = 4;
	const ITALICS = 5;
	const BOLDS = 6;
	const SCOPED_BACKGROUND = 7;
	const LANGUAGE_SPECIFIC_SCOPES = 8;
	const SCROLLBAR_INDICATORS = 9;
	const LINE_HIGHLIGHTING = 10;
	const CARRET_CUSTOMIZATION = 11;
	const LINE_NUMBERS_CUSTOMIZATION = 12;
	const INDENT_GUIDES_CUSTOMIZATION = 13;
	const MARGIN_GUTTER_CUSTOMIZATION = 14;
	const SELECTION_CUSTOMIZATION = 15;
	const SEARCH_HIGHLIGHT_CUSTOMIZATION = 16;
	const MATCHING_BRACKETS_CUSTOMIZATION = 17;
	const SCOPED_FONT = 18;
}
